ARG ELIXIR_VERSION=1.16.2
ARG OTP_VERSION=26.2.3

FROM elixir:${ELIXIR_VERSION}-slim
LABEL maintainer="Eramoss <edulramos@outlook.com>"

WORKDIR /app

RUN apt-get update -y && apt-get install -y build-essential git \
    && apt-get clean && rm -f /var/lib/apt/lists/*_*

COPY . /app/

RUN mix deps.get
RUN mix assets.setup
RUN mix deps.compile

# make sure that the database is configured and referenced at env file
RUN mix ecto.create

EXPOSE 4000

CMD ["iex", "-S", "mix", "phx.server"]
