ARG ELIXIR_VERSION=1.16.2
ARG OTP_VERSION=26.2.3

FROM elixir:${ELIXIR_VERSION}-slim
LABEL maintainer="Eramoss <edulramos@outlook.com>"

WORKDIR /app

ARG UID=1000
ARG GID=1000

RUN apt-get update -y && apt-get install -y build-essential git \
    && apt-get clean && rm -f /var/lib/apt/lists/*_*


# install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# install mix dependencies
COPY mix.exs mix.lock ./
RUN mix deps.get
RUN mkdir config

# copy compile-time config files before we compile dependencies
# to ensure any relevant config change will trigger the dependencies
# to be re-compiled.
COPY config/config.exs config/dev.exs config/
RUN mix deps.compile

COPY priv priv

COPY lib lib

COPY assets assets

# compile assets
RUN mix assets.deploy

# Compile the release
RUN mix compile
EXPOSE 4000

CMD ["iex", "-S", "mix", "phx.server"]
